### ISSUE TITLE
Bug: Invisible HTML blocks

### ISSUE THREAD

**Issue by Kristoffeh** [turbosnail/lfspolygon#5]
There are invisible objects on the left side of the screen when being zoomed in (ctrl+scroll is used). This is quite a major bug, because when drawing polygons it does get quite annoying.

Great work though!

![last ned](https://user-images.githubusercontent.com/10790999/79573492-076e4f00-80bf-11ea-842f-d9e9f6faf911.png)

**Comment by turbosnail** [comment]
this blocks in parent block have id work
first block .control_block make this width
![image](https://user-images.githubusercontent.com/6097518/79971512-12e5bf80-849d-11ea-853c-aa8e5904661f.png)

i will fix that
